<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderDetail extends Model
{
    protected $table = 'OrderDetail';

    public function find($orderId, $productId, $columns = ['*'])
    {
        return $this->where([
            'OrderId' => $orderId,
            'ProductId' => $productId,
        ])->first($columns);

    }

    public function getKeyName()
    {
        // for sqlite
        return "OrderId || '_' ||  ProductId";
    }

    protected function getKeyForSaveQuery()
    {
        return isset($this->original['OrderId'])
            ? $this->original['OrderId'] . '_' . $this->original['ProductId']
            : $this->attributes['OrderId'] . '_' . $this->attributes['ProductId'];
    }

    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function order()
    {
        return $this->belongsTo(Order::class, 'OrderId', 'Id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'ProductId', 'Id');
    }
}